<a href="https://colab.research.google.com/github/Yassaadel/Depi.gov/blob/master/Task%20Data%20Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random
import numpy as np

# Generate a list of random integers
random_data = [random.randint(1, 100) for _ in range(20)]
print("Random Data:", random_data)

# Convert the list to a numpy array
np_data = np.array(random_data)

# Inspecting the array
print("\nInspecting the Array:")
print("Shape:", np_data.shape)
print("Length:", len(np_data))
print("Size:", np_data.size)
print("Data Type:", np_data.dtype)

# Reshaping the array
reshaped_data = np_data.reshape(4, 5)
print("\nReshaped Data (4x5):\n", reshaped_data)

# Basic statistics
print("\nBasic Statistics:")
mean = np.mean(np_data)
median = np.median(np_data)
std_dev = np.std(np_data)
variance = np.var(np_data)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

# Min and Max
min_value = np.min(np_data)
max_value = np.max(np_data)
print("Min Value:", min_value)
print("Max Value:", max_value)

# Sum and Product
total_sum = np.sum(np_data)
total_product = np.prod(np_data)
print("Total Sum:", total_sum)
print("Total Product:", total_product)

# Sorting
sorted_data = np.sort(np_data)
print("\nSorted Data:", sorted_data)

# Unique values and their counts
unique_values, counts = np.unique(np_data, return_counts=True)
print("\nUnique Values:", unique_values)
print("Counts of Unique Values:", counts)

# Comparison operations
greater_than_50 = np_data > 50
print("\nElements Greater Than 50:", greater_than_50)
print("Data Elements Greater Than 50:", np_data[greater_than_50])

# Aggregation functions
sum_along_axis_0 = np.sum(reshaped_data, axis=0)
sum_along_axis_1 = np.sum(reshaped_data, axis=1)
print("\nSum Along Axis 0:", sum_along_axis_0)
print("Sum Along Axis 1:", sum_along_axis_1)

# Additional manipulations
# Transpose of the reshaped data
transposed_data = reshaped_data.T
print("\nTransposed Data:\n", transposed_data)

# Flattening the reshaped data
flattened_data = reshaped_data.flatten()
print("Flattened Data:", flattened_data)

# Changing array shape
reshaped_again_data = np_data.reshape(5, 4)
print("\nReshaped Again Data (5x4):\n", reshaped_again_data)

# Adding elements
added_element_data = np.append(np_data, [101, 102, 103])
print("Data After Adding Elements:", added_element_data)

# Removing elements
removed_element_data = np.delete(np_data, [0, 1, 2])
print("Data After Removing Elements:", removed_element_data)

# Splitting the array
split_data = np.split(np_data, 4)
print("\nSplit Data into 4 parts:", split_data)

# Combining data (concatenation)
concatenated_data = np.concatenate((np_data, np_data))
print("Concatenated Data:", concatenated_data)

# Stack arrays vertically and horizontally
vstacked_data = np.vstack((reshaped_data, reshaped_data))
hstacked_data = np.hstack((reshaped_data, reshaped_data))
print("\nVertically Stacked Data:\n", vstacked_data)
print("Horizontally Stacked Data:\n", hstacked_data)

# Combining data (column stack)
col_stacked_data = np.column_stack((np_data, np_data))
print("\nColumn Stacked Data:\n", col_stacked_data)


Random Data: [92, 44, 72, 57, 8, 41, 78, 40, 89, 27, 43, 1, 89, 15, 94, 77, 68, 67, 95, 68]

Inspecting the Array:
Shape: (20,)
Length: 20
Size: 20
Data Type: int64

Reshaped Data (4x5):
 [[92 44 72 57  8]
 [41 78 40 89 27]
 [43  1 89 15 94]
 [77 68 67 95 68]]

Basic Statistics:
Mean: 58.25
Median: 67.5
Standard Deviation: 28.78693279944913
Variance: 828.6875
Min Value: 1
Max Value: 95
Total Sum: 1165
Total Product: 2724384583011794944

Sorted Data: [ 1  8 15 27 40 41 43 44 57 67 68 68 72 77 78 89 89 92 94 95]

Unique Values: [ 1  8 15 27 40 41 43 44 57 67 68 72 77 78 89 92 94 95]
Counts of Unique Values: [1 1 1 1 1 1 1 1 1 1 2 1 1 1 2 1 1 1]

Elements Greater Than 50: [ True False  True  True False False  True False  True False False False
  True False  True  True  True  True  True  True]
Data Elements Greater Than 50: [92 72 57 78 89 89 94 77 68 67 95 68]

Sum Along Axis 0: [253 191 268 256 197]
Sum Along Axis 1: [273 275 242 375]

Transposed Data:
 [[92 41 43 77]
 [44 78  1 68]
 [72